### PR TITLE
[WIP] Implements Garbage Collection metrics

### PR DESCRIPTION
**Pull request by PauloPaquielli**
# Describe:

The metrics of GC stats, invoke the exported function to create the metrics, then invoke the returned function to start the collecting.

### This module exposes 3 metrics:

nodejs_gc_runs_total: Counts the number of time GC is invoked
nodejs_gc_pause_seconds_total: Time spent in GC in seconds
nodejs_gc_reclaimed_bytes_total: The number of bytes GC has freed

### Pending

Making tests.

### CODE REVIEW

**Comment by disjunction** [comment]
Hi, sorry, please keep in mind - this is express-related library. You can get other metrics by using `prom-client` directly. 

Here you have a few of them: https://github.com/siimon/prom-client/tree/master/lib/metrics

Please refer prom-client directly. I won't merge not directly express-related parts into this library.

**Comment by PauloPaquielli** [comment]
Hello @disjunction,

I need your help as I think it's worth implementing these basic metrics gc, currently it already exposes all the metrics you mentioned by default, only 3 metrics were separated and another lib (https://github.com/siimon/prom -client#garbage-collection). I tried to implement, but it did not register the metrics.

**Comment by disjunction** [comment]
@PauloPaquielli it might be because of the version conflict. prom-client current version is 7.x, while express-prom-bundle still relies on 6.x, so if you do `requir('prom-client')` in your app, you can potentially require a different prom-client singleton, than the one in the `express-prom-bundle`.

Could you try using the promClient exported by the prom-express-bundle?

```javascript
const promBundle = requrie('express-prom-bundle`);
const promClient = promBundle.promClient;
const myMetric = new promClient.Counter( /* ... */ );
```

**Comment by PauloPaquielli** [comment]
@disjunction Yes and it worked! But the problem is that I have several applications on node with express and I will have to repeat this several times. So I thought about grouping all the basic node-express metrics into a single lib would be awesome and easy and maybe it would help other people :)

Unfortunately the lib I showed you is not able to use another prom-client :(

**Comment by disjunction** [comment]
Actually node-prometheus-gc-stats has a **peer** dependency on prom-client, so it should use the same prom-client. I'm afraid you'll have to debug it a bit deeper. You may want to try `proxyquire` to force the lib when initializing the node-prometheus-gc-stats, but it'll be ugly. 

From my side I can try to rollout 3.x version of this lib making prom-client also a peer dependency  and then it will be completely up to the user. Sorry, I'm lately quite busy with other stuff on my plate :\

**Comment by PauloPaquielli** [comment]
Hello @disjunction,

No problems. I tried to improve the implementation by putting "node-prometheus-gc-stats" as a dependency instead of re-implementing it.

I think this is simple to implement and maintain, besides being a small change :)

What do you think ?

This weekend I will finish the tests and describe the changes in the README of the other PR. 👊 

Is there any improvement I could help you with?

**Comment by disjunction** [comment]
Sorry, as mentioned above - it's a nice solution, but it's a special case which i won't accept into the lib. You can publish it in npm with some other name if you like.

**Comment by disjunction** [comment]
are you ok with me closing this PR?

**Comment by PauloPaquielli** [comment]
Hello @disjunction ,

I'm a little busy, in period of University tests: /.

I opened a pr to the gc-status lib: https://github.com/SimenB/node-prometheus-gc-stats/pull/19 and it looks like I'm going to solve the problem

You may close, but I still think it would be nice to have this feature on the lib :)

I can improve and integrate something more elegant, what do you think?

**Comment by disjunction** [comment]
Thanks for quick reply. I still think GC is to special case to be included in this lib. It does belong to the main metrics collection of prom-client. Cheers!

**Pull request closed without merging**
