### PR TITLE
feat: respect pruneAgedBuckets

### PR DESCRIPTION
**Pull request by timm-stelzer-e-farm**

### CODE REVIEW

**Comment by disjunction** [comment]
Hi Timm. This looks like a nice feature. I will test and integrate it in the coming days.

Yet I'm a bit concerned about bumping the required prom-client version. It will make a lot of existing projects incompatible. I wonder if having the support for the `pruneAgedBuckets` has any problems with the older client? I would expect not, in other words if people have the new prom-client then it will work, otherwise just ignored. What do you think?

**Comment by timm-stelzer-e-farm** [comment]
> Yet I'm a bit concerned about bumping the required prom-client version.
Yes, I agree, and as a user I would probably expect a major version bump for this.

> has any problems with the older client?
Couldn't say, @rilpires implemented it in prom-client, AFAIK.

**Comment by rilpires** [comment]
Just my 2 cents,
> From briefly looking at the code, I would expect the option to be simply ignored
Yes, it will be simply ignored. It is just a _Object.assign_ on top of a default config object

> So maybe we don't need the prom-client version bump here.
Well, the `pruneAgedBuckets` feature just won't be available then.

**Comment by disjunction** [comment]
Merged manually. Thanks for contributing. This was released in [v7.0.0](https://github.com/jochen-schweizer/express-prom-bundle/releases/tag/7.0.0)

**Pull request closed without merging**
