### PR TITLE
Format Status Code

### PR DESCRIPTION
**Pull request by PauloPaquielli**
I need to format the status to be in a standard format used in some internal projects and I could not find a way to do this without making a change in the project :(

image

I did it in a simple way already implementing the same way as `NormalizePath`. I hope you enjoy. :)

### CODE REVIEW

**Comment by disjunction** [comment]
Hello @PauloPaquielli 
thanks for for the PR! I have some concerns before merging though:
1) have you considered prometheus relabeling feature. At least from the test you provided it looks like you could aggregate the errors there, while still keeping the possibility to drill down to actual codes from say a dev. prometheus. In your case i'd imaging something like:

```
   - source_labels: ["status_code"]
        regex: "5.*"
        target_label: "status_code"
        replacement: "5xx"
```

2) I'd still do the hook you suggest, but make it more geenric. So that the function gest the whole object with all labels and transforms all of them it pleases. M.b. something like `transformLabels` instead of `normalizeStatus`

What do you think?

**Comment by PauloPaquielli** [comment]
Hello @disjunction, 

1 - The problem is the excess of metrics. Currently haproxy already registers the status_code in this way. I think I do not currently need a generic function to format all the labels, since we only have implemented path, status_code, method, where we have `normalizePath` and the method I think is unlikely anyone wants to format. I'm currently implementing the code this way:
````
const groupRoutes = [
    { regex: /^\/css/, route: '/css' },
    { regex: /^\/js/, route: '/js' },
  ];

  const { normalizePath } = promBundle;
  promBundle.normalizePath = (req, opts) => {
    const normalizedPath = normalizePath(req, opts);
    for (const { regex, route } of groupRoutes) {
      if (normalizedPath.match(regex)) return route;
    }
    return normalizedPath;
  };

  promBundle.normalizeStatusCode = (res) => {
    const statusCode = ({
      1: '1xx',
      2: '2xx',
      3: '3xx',
      4: '4xx',
      5: '5xx',
    })[String(res.statusCode).charAt(0)] || 'other';
    return statusCode;
  };
`````

I really liked the idea of ​​implementing `transformLabels` and unify the formatting of labels. I can improve this code later and implement something like this:

````
PromBundle.transformLabels = [
    {Target_label: 'path', regex: /^\/css/, replace: '/ css'},
    {Target_label: 'path', regex: /^\/js/, replace: '/ js'},
    {Target_label: 'status_code', regex: /^1.*/, replace: '1xx'},
    {Target_label: 'status_code', regex: /^2.*/, replace: '2xx'},
    {Target_label: 'status_code', regex: /^3.*/, replace: '3xx'},
    {Target_label: 'status_code', regex: /^4.*/, replace: '4xx'},
    {Target_label: 'status_code', regex: /^5.*/, replace: '5xx'},
    {Target_label: 'status_code', regex: /^[0,6-9].*/, replace: 'other'},
  ];
````

What do you think ?

Could we integrate the PR and make this improvement in the future?

**Comment by disjunction** [comment]
ok, convinced. I've merged and published in npm as version 2.2.0

But there is some work I'll do with it and release a patch version:

1. the test coverage went down from 100% to 99%. Nothing critical, but i'd like to fix it. You can run it yourself if you want: `make coverage`

2. Need to add it to the README.md

let me know if you want to take over any of those, otherwise i proceed myself

Cheers

**Comment by PauloPaquielli** [comment]
Thanks @disjunction !!!

I can add it to README.md quickly, since the improvement of the tests should take a little longer, but I do.

:)

**Pull request merged**
